# Generated by Django 2.2.6 on 2019-10-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191024_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='class_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Номер пары'),
        ),
    ]
