# Generated by Django 2.2.6 on 2019-10-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10, verbose_name='Auditoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Imya prepodovatelya')),
                ('department', models.TextField(max_length=50, verbose_name='Kafedra prepodavatelya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email prepodavatelya')),
                ('phone_number', models.TextField(max_length=50, verbose_name='Telefon prepodavatelya')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10, verbose_name='Gruppa')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Predmet')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(verbose_name='Nomer pari')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Classroom')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Speaker')),
                ('study_group', models.ManyToManyField(to='schedule.StudyGroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject')),
            ],
        ),
    ]
