# Generated by Django 2.2.6 on 2019-10-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_day',
            field=models.DateField(auto_now=True, verbose_name='Дата занятия'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.TextField(max_length=10, unique=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='class_number',
            field=models.IntegerField(verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Speaker', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='study_group',
            field=models.ManyToManyField(to='schedule.StudyGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='department',
            field=models.TextField(blank=True, max_length=50, verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.TextField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='phone_number',
            field=models.TextField(blank=True, max_length=20, verbose_name='Номер телефона преподавателя'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.TextField(max_length=10, unique=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(max_length=100, unique=True, verbose_name='Предмет'),
        ),
    ]
