# Generated by Django 2.2.6 on 2019-10-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191024_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_day',
            field=models.DateField(verbose_name='Дата занятия'),
        ),
    ]
