# Generated by Django 2.2.6 on 2019-10-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20191024_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='study_group',
        ),
        migrations.AddField(
            model_name='lesson',
            name='study_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.StudyGroup', verbose_name='Группа'),
        ),
    ]
