# Generated by Django 2.2.6 on 2019-10-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20191024_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.StudyGroup', verbose_name='Группа'),
        ),
    ]
