# Generated by Django 2.2.6 on 2019-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20191024_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона преподавателя'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Предмет'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('class_number', 'study_group', 'date_day')},
        ),
    ]
