# Generated by Django 2.2.6 on 2019-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20191104_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondata',
            name='weeks',
            field=models.TextField(default=[]),
        ),
    ]
