# Generated by Django 2.2.6 on 2019-11-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_commondata_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=10)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='commondata',
            options={'verbose_name': 'Common Data', 'verbose_name_plural': 'Common Data'},
        ),
    ]
