# Generated by Django 2.2.6 on 2020-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20191105_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonData',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date_day'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='weeks',
            options={'verbose_name_plural': 'Weeks'},
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('Лекция', 'Lecture'), ('Практика', 'Practice'), ('Лабораторная работа', 'Lab')], default=None, max_length=40, null=True, verbose_name='Тип занятия'),
        ),
    ]
