# Generated by Django 2.2.6 on 2020-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20200321_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Название предмета', max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'subject_type')},
        ),
    ]
