# Generated by Django 2.2.6 on 2020-03-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20200321_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.CharField(blank=True, choices=[('mon', 'пн'), ('tue', 'вт'), ('wed', 'ср'), ('thu', 'чт'), ('fri', 'пт'), ('sat', 'сб')], max_length=10, null=True, verbose_name='День'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week_parity',
            field=models.CharField(blank=True, choices=[('even', 'Четная'), ('uneven', 'Нечетная')], max_length=10, null=True, verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='mode_of_study',
            field=models.CharField(blank=True, choices=[('fulltime', 'Дневная'), ('distance', 'Заочная')], max_length=20, null=True, verbose_name='Форма обучения'),
        ),
    ]
