# Generated by Django 2.2.6 on 2020-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20200323_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата занятия'),
        ),
    ]
