# Generated by Django 2.2.6 on 2020-03-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20200323_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Номер пары')),
                ('week_parity', models.CharField(blank=True, choices=[('even', 'Четная'), ('uneven', 'Нечетная')], max_length=10, null=True, verbose_name='Неделя')),
                ('day', models.CharField(blank=True, choices=[('mon', 'пн'), ('tue', 'вт'), ('wed', 'ср'), ('thu', 'чт'), ('fri', 'пт'), ('sat', 'сб')], max_length=10, null=True, verbose_name='День')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Classroom', verbose_name='Аудитория')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Speaker', verbose_name='Преподаватель')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.StudyGroup', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Занятие заочное',
                'verbose_name_plural': 'Занятия заочные',
                'ordering': ['day'],
                'unique_together': {('class_number', 'study_group', 'week_parity', 'day')},
            },
        ),
        migrations.CreateModel(
            name='LessonFulltime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Номер пары')),
                ('date_day', models.DateField(blank=True, null=True, verbose_name='Дата занятия')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Classroom', verbose_name='Аудитория')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Speaker', verbose_name='Преподаватель')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.StudyGroup', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Занятие дневное',
                'verbose_name_plural': 'Занятия дневные',
                'ordering': ['date_day'],
                'unique_together': {('class_number', 'study_group', 'date_day')},
            },
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
