# Generated by Django 2.2.6 on 2020-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_load_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondistance',
            name='term',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=2, null=True, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='term',
            name='weeks_count_distance',
            field=models.CharField(blank=True, max_length=5, verbose_name='Кол-во недель (вечернее)'),
        ),
        migrations.AlterField(
            model_name='term',
            name='weeks_count_fulltime',
            field=models.CharField(blank=True, max_length=5, verbose_name='Кол-во недель (дневное)'),
        ),
        migrations.AlterUniqueTogether(
            name='load',
            unique_together={('term', 'group', 'subject')},
        ),
    ]
