# Generated by Django 2.2.6 on 2020-04-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_auto_20200402_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonfulltime',
            name='term',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=2, null=True, verbose_name='Семестр'),
        ),
    ]
