# Generated by Django 2.2.6 on 2020-04-04 15:59

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_auto_20200402_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondistance',
            name='date_day',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 1, 9)), django.core.validators.MaxValueValidator(datetime.date(2020, 1, 25))], verbose_name='Дата занятия'),
        ),
        migrations.AlterField(
            model_name='lessondistance',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Term', verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='lessonfulltime',
            name='day',
            field=models.CharField(choices=[('Mon', 'пн'), ('Tue', 'вт'), ('Wed', 'ср'), ('Thu', 'чт'), ('Fri', 'пт'), ('Sat', 'сб')], max_length=10, null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='lessonfulltime',
            name='term',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=2, null=True, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='lessonfulltime',
            name='week_parity',
            field=models.CharField(choices=[('even', 'Четная'), ('uneven', 'Нечетная')], max_length=10, null=True, verbose_name='Неделя'),
        ),
    ]
