# Generated by Django 2.2.6 on 2020-04-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_auto_20200404_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfulltime',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Term', verbose_name='Семестр'),
        ),
    ]
